### ISSUE TITLE
Hi! How do I determine the number of changed characters or words?

### ISSUE THREAD

**Issue by pastukhov-aleksandr** [jfcherng/php-diff#39]
Hi! How do I determine the number of changed characters or words? Thanks

**Comment by jfcherng** [comment]
That information is not necessary included in this package during calculating the diff since it can be line-based. In that case, it only knows changed lines.

Generally, I feel you want https://packagist.org/packages/jfcherng/php-sequence-matcher. Unfortunately I don't think people will use it so there is no docs. But test cases speak, https://github.com/jfcherng/php-sequence-matcher/blob/369933b7cfbc31979fd94bf6391451468f49c693/tests/SequenceMatcherTest.php#L196-L203. To know how many words have been changed, your job is to cut the old/new strings into word-base array like the test case. `getOpcodes()` will return the sequence diff (opcodes). 

The opcode is in the form of `[operation, old_idx_begin, old_idx_end (exclusive), new_idx_begin, new_idx_end (exclusive)]`. For example, `[SequenceMatcher::OP_DEL, 1, 3, 1, 1],` means old items 1\~3(exclusive) should be deleted and new items 1\~1(exclusive, 1\~1 means nothing since this is a "delete" operation, which won't modify the new items) should be deleted. `[SequenceMatcher::OP_REP, 1, 2, 1, 3],` means old items 1\~2(exclusive) should be replaced by the new items 1\~3(exclusive).

**Comment by pastukhov-aleksandr** [comment]
Thanks!
